language: python
python:
  - "3.8"
script: python setup.py test
env:
  global:
    - secure: "jeWIlhe2d96C19AzNezPT2jZ4KYobdNShJSAalD1JnLS5venGMufb+/RgRk91hNkli3UBqQa7lfJ3VQ/V0/GKXQSn4Y9C9ebgISTA8afR3Ix5d3HSAdKcUtyLGVNvIojJxwycH+CldgTVa2LxwLr0BZd7y0C5Jdz5ndIJo1BrZs="
    - secure: "G1edtG6la0DwKLJ75hfcazjnYLoE7fvwRaQepfrn9xAqj/TGFw3sBCGfm4WaY3d+K7jLfcXI+FgNQM3+H6I0HJWCCE2nB6mDjuxk2yIy0V9csyh414HGlgSFZ5TpXXlKeJpE/qoHdnZiKxo6c10H4Fv6BDSUxGuu1RxI8bPxHt0="
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user:
    secure: "VZ0pVItAFY0dft3y2jpaHuZ9ffSNQhrrGtSflxnKM3VuxM87hbQFY7J7iy1ZntS2hEsqniWHCn1jHF12tn76yGo+7qPd9F47/6Xz4wbWTqbDL/oAoqVcXmAnori/LEgYUkwsWP3PzfhZomOMQJfs/4MDlqLzL2Wf4A2hGMZNlUI="
  password: $T1$T2
  on:
    repo: kichik/pyndef
    tags: true
    python: 3.8
